# Generated by Django 2.2.7 on 2019-11-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20191114_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
