# Generated by Django 2.2.7 on 2019-11-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_ordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenador',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
