# Generated by Django 2.2.7 on 2019-11-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_ordenador_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests1', models.ManyToManyField(blank=True, to='biblioteca.Test1')),
            ],
        ),
        migrations.AddField(
            model_name='test1',
            name='tests2',
            field=models.ManyToManyField(blank=True, to='biblioteca.Test2'),
        ),
    ]
