# Generated by Django 2.2.7 on 2019-11-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20191129_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='test2',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
