# Generated by Django 2.2.8 on 2019-12-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_auto_20191213_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(blank=True, help_text='Select a genre for this book', null=True, to='biblioteca.Genero'),
        ),
    ]
