# Generated by Django 2.2.7 on 2019-11-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
